"""
cyber/standards/stix/enums.py

STIX Enums.
"""
from enum import Enum


class StixObjectType(Enum):
    """STIX object types."""
    ATTACK_PATTERN = "attack-pattern"
    CAMPAIGN = "campaign"
    COURSE_OF_ACTION = "course-of-action"
    IDENTITY = "identity"
    INDICATOR = "indicator"
    INFRASTRUCTURE = "infrastructure"
    INTRUSION_SET = "intrusion-set"
    MALWARE = "malware"
    MARKING_DEFINITION = "marking-definition"
    NOTE = "note"
    OPINION = "opinion"
    RELATIONSHIP = "relationship"
    REPORT = "report"
    THREAT_ACTOR = "threat-actor"
    TOOL = "tool"
    VULNERABILITY = "vulnerability"
    X509_CERTIFICATE = "x509-certificate"
    AUTONOMOUS_SYSTEM = "autonomous-system"
    DIRECTORY = "directory"
    DNS_RECORD = "dns-record"
    DOMAIN_NAME = "domain-name"
    EMAIL_ADDR = "email-addr"
    EMAIL_MESSAGE = "email-message"
    EMAIL_MIME_PART_TYPE = "email-mime-part-type"
    FILE = "file"
    IPv4_ADDRESS = "ipv4-addr"
    IPv6_ADDRESS = "ipv6-addr"
    MAC_ADDRESS = "mac-addr"
    NETWORK_TRAFFIC = "network-traffic"
    PROCESS = "process"
    SOFTWARE = "software"
    URL = "url"
    USER_ACCOUNT = "user-account"
    WINDOWS_REGISTRY_KEY = "windows-registry-key"
    WINDOWS_REGISTRY_VALUE_TYPE = "windows-registry-value-type"
    CRYPTOGRAPHIC_KEY = "cryptographic-key"
    CRYPTOCURRENCY_WALLET = "cryptocurrency-wallet"
    TEXT = "text"
    ARTIFACT = "artifact"
    CANONICAL_SHA_256 = "canonical-sha-256"
    CUSTOM = "custom"


class StixRelationshipType(Enum):
    """STIX relationship types."""
    USES = "uses"
    USED_BY = "used-by"
    DELIVERS = "delivers"
    DELIVERED_BY = "delivered-by"
    HOSTS = "hosts"
    HOSTED_BY = "hosted-by"
    ORIGINATES_FROM = "originates-from"
    COMMUNICATES_WITH = "communicates-with"
    CONSISTS_OF = "consists-of"
    CONTAINS = "contains"
    CONTROLLED_BY = "controlled-by"
    CONTROLS = "controls"
    CO_LOCATES_WITH = "co-locates-with"
    CORRELATES = "correlates"
    CREATED_BY = "created-by"
    DERIVES_FROM = "derives-from"
    DETECTS = "detects"
    DETECTED_BY = "detected-by"
    DOWNLOADS = "downloads"
    DOWNLOADED_BY = "downloaded-by"
    DROPS = "drops"
    DROPPED_BY = "dropped-by"
    EXPLOITS = "exploits"
    EXPLOITED_BY = "exploited-by"
    HAS = "has"
    IMPERSONATES = "impersonates"
    INDICATES = "indicates"
    INVESTIGATES = "investigates"
    INVOLVED_IN = "involved-in"
    LOCATES = "locates"
    LOCATED_ON = "located-on"
    MITIGATES = "mitigates"
    MITIGATED_BY = "mitigated-by"
    OWNS = "owns"
    OWNED_BY = "owned-by"
    PARTICIPATES_IN = "participates-in"
    REBUILDS = "rebuilds"
    RELATED_TO = "related-to"
    REMEDIATES = "remediates"
    REVIEWED_BY = "reviewed-by"
    RUNS = "runs"
    RUNS_ON = "runs-on"
    SENT = "sent"
    SENT_FROM = "sent-from"
    SENT_TO = "sent-to"
    SPECIFIC_TO = "specific-to"
    STEPS_IN = "steps-in"
    TARGETS = "targets"
    TARGETED_BY = "targeted-by"
    TYPE_OF = "type-of"
    VARIANT_OF = "variant-of"


class StixMarkingType(Enum):
    """STIX marking definition types."""
    TLP_WHITE = "TLP:WHITE"
    TLP_GREEN = "TLP:GREEN"
    TLP_AMBER = "TLP:AMBER"
    TLP_RED = "TLP:RED"
    STATEMENT = "statement"
    CANONICAL = "canonical"
