"""
intelligence/capabilities/agents/reporting.py

Reporting Agent.

Reference agent for reporting capability.
"""
from __future__ import annotations

from intelligence.capabilities.agents.base import BaseAgent
from intelligence.capabilities.models import (
    CapabilityTask,
    CapabilityResult,
    CapabilityType,
    FindingType,
)


class ReportingAgent(BaseAgent):
    """Reporting capability agent."""
    
    agent_type: str = "reporting"
    name: str = "Reporting Agent"
    description: str = "Generic reporting capability agent"
    capability_type = CapabilityType.REPORTING
    
    def _generate_outputs(self, task: CapabilityTask) -> dict[str, Any]:
        report_format = task.inputs.get("format", "text")
        return {
            "agent_id": self.agent_id,
            "agent_type": self.agent_type,
            "task_id": task.task_id,
            "format": report_format,
            "executed": True,
            "output_type": "report",
        }
    
    def execute(self, task: CapabilityTask) -> CapabilityResult:
        result = super().execute(task)
        finding = self.create_finding(
            title="Report generated",
            description="Reporting capability executed",
            finding_type=FindingType.OBSERVATION,
            confidence=0.9,
        )
        result.add_finding(finding)
        result.outputs["report_content"] = "# Report\nGenerated by reporting agent."
        return result
